### ISSUE TITLE
Width/Heigth mismatch

### ISSUE THREAD

**Issue by big-charles** [Abe404/root_painter#56]
**Describe the bug**
RootPainter seems to invert the width and heigth when loading the image. This causes in the getitem func of the torch dataset to crash Traceback (most recent call last):                                                            │nd,no seg found,no seg found,no seg found,no seg found,no seg found,no seg found,no seg found
  File "trainer/main.py", line 33, in <module>                                                │,no seg found,no seg found,no seg found,no seg found,no seg found,no seg found,no seg found,n
    trainer.main_loop()                                                                       │o seg found,no seg found,no seg found,no seg found,no seg found,no seg found,no seg found,no
  File "/CECI/home/users/r/o/rongione/root_painter/trainer/trainer.py", line 105, in main_loop│seg found,no seg found,no seg found,no seg found,no seg found,no seg found,no seg found,no se
    self.train_one_epoch()                                                                    │g found,no seg found,no seg found,no seg found,no seg found,no seg found,no seg found,no seg
  File "/CECI/home/users/r/o/rongione/root_painter/trainer/trainer.py", line 234, in train_one│found,no seg found,no seg found,no seg found,no seg found,no seg found,no seg found,no seg fo
_epoch                                                                                        │und,no seg found,no seg found,no seg found,no seg found,no seg found,no seg found,no seg foun
    for step, (photo_tiles,                                                                   │d,no seg found,no seg found,no seg found,no seg found,no seg found,no seg found,no seg found,
  File "/home/ucl/elia/rongione/.local/lib/python3.8/site-packages/torch/utils/data/dataloader│no seg found,no seg found,no seg found,no seg found,no seg found,no seg found,no seg found,no
.py", line 517, in __next__                                                                   │ seg found,no seg found,no seg found,no seg found,no seg found,no seg found,no seg found,no s
    data = self._next_data()                                                                  │eg found,no seg found,no seg found,no seg found,no seg found,no seg found,no seg found,no seg
  File "/home/ucl/elia/rongione/.local/lib/python3.8/site-packages/torch/utils/data/dataloader│ found,no seg found,no seg found,load seg from file.
.py", line 1199, in _next_data                                                                │no seg found,no seg found,no seg found,no seg found,no seg found,no seg found,no seg found,no
    return self._process_data(data)                                                           │ seg found,no seg found,no seg found,no seg found,no seg found,no seg found,no seg found,no s
  File "/home/ucl/elia/rongione/.local/lib/python3.8/site-packages/torch/utils/data/dataloader│eg found,no seg found,no seg found,no seg found,no seg found,no seg found,no seg found,no seg
.py", line 1225, in _process_data                                                             │ found,no seg found,no seg found,no seg found,no seg found,no seg found,no seg found,no seg f
    data.reraise()                                                                            │ound,no seg found,no seg found,no seg found,no seg found,no seg found,no seg found,no seg fou
  File "/home/ucl/elia/rongione/.local/lib/python3.8/site-packages/torch/_utils.py", line 429,│nd,no seg found,no seg found,no seg found,no seg found,no seg found,no seg found,no seg found
 in reraise                                                                                   │,no seg found,no seg found,no seg found,no seg found,no seg found,no seg found,no seg found,n
    raise self.exc_type(msg)                                                                  │o seg found,no seg found,no seg found,no seg found,no seg found,no seg found,no seg found,no
AssertionError: Caught AssertionError in DataLoader worker process 0.                         │seg found,no seg found,no seg found,no seg found,no seg found,no seg found,no seg found,no se
Original Traceback (most recent call last):                                                   │g found,no seg found,no seg found,no seg found,no seg found,no seg found,no seg found,no seg
  File "/home/ucl/elia/rongione/.local/lib/python3.8/site-packages/torch/utils/data/_utils/wor│found,no seg found,no seg found,no seg found,no seg found,no seg found,no seg found,no seg fo
ker.py", line 202, in _worker_loop                                                            │und,no seg found,no seg found,no seg found,no seg found,no seg found,no seg found,no seg foun
    data = fetcher.fetch(index)                                                               │d,no seg found,no seg found,no seg found,no seg found,no seg found,no seg found,no seg found,
  File "/home/ucl/elia/rongione/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fet│no seg found,no seg found,no seg found,no seg found,no seg found,no seg found,load seg from f
ch.py", line 44, in fetch                                                                     │ile.
    data = [self.dataset[idx] for idx in possibly_batched_index]                              │Traceback (most recent call last):
  File "/home/ucl/elia/rongione/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fet│  File "/home/Charles/root_painter/painter/src/main/python/plot_seg_metrics.py", line 185, in
ch.py", line 44, in <listcomp>                                                                │ run
    data = [self.dataset[idx] for idx in possibly_batched_index]                              │    metrics = compute_seg_metrics(self.seg_dir, self.annot_dir, fname)
  File "/CECI/home/users/r/o/rongione/root_painter/trainer/datasets.py", line 138, in __getite│  File "/home/Charles/root_painter/painter/src/main/python/plot_seg_metrics.py", line 141, in
m__                                                                                           │ compute_seg_metrics
    assert annot_tile.shape == (self.in_w, self.in_w, 2), (                                   │    corrected[foreground > 0] = 1
AssertionError:  shape is (572, 487, 2) for tile from 2T4_20210502_111453.png

![bug rp](https://user-images.githubusercontent.com/70576282/196466245-62d6c60d-7a51-4666-8c2c-7a6fb6ca5c56.png)
![rp bug](https://user-images.githubusercontent.com/70576282/196466252-292f0181-3082-475e-a415-8ee8eeb3e4bd.png)

**To Reproduce**
1. Create a dataset with this image
2. Annotate it
3. Launch training

This is one of the images for which this bug happens

![16T4_20210507_183429](https://user-images.githubusercontent.com/70576282/196466385-4be5cc10-ecc5-4a33-b2f8-b765fd8096a1.jpg)

**Comment by Abe404** [comment]
Thanks for reporting this. The image appears to have some unusual orientation information in the EXIF metadata.

I have implemented a fix based on https://github.com/python-pillow/Pillow/issues/4703#issuecomment-645219973

And will hopefully have it in master before the end of today.

**Comment by Abe404** [comment]
Fixed in:

https://github.com/Abe404/root_painter/commit/9893d23c7510e9c0792c86995fabdbcb956791c6

I also removed the code that repeated logs 'no seg found' as that's not helpful for the debug output.
