### ISSUE TITLE
Installing Root_trainer on an M1 Max Apple Silicon

### ISSUE THREAD

**Issue by sck-at-ucy** [Abe404/root_painter#86]
Hi Abraham, 

Is there a way to install the server on a Mac using Apple Silicon (M1 Max) to take advantage of the GPU directly and not use Rozetta emulation? Any help to get started would be highly appreciated.

**Comment by Abe404** [comment]
From https://pytorch.org/get-started/locally/ and
https://developer.apple.com/metal/pytorch/

It looks like macOS 12.3 or later is required.

**Comment by rohanorton** [comment]
Had an attempt at implement this. See commit message in https://github.com/Abe404/root_painter/commit/935fd6a3ff6f9684c03a9387fa6c7ba2ee873108 for summary of some what was done and the issues

**Comment by sck-at-ucy** [comment]
This is very helpful, I was also down the path of using ".to(device)" but was stuck with torch.loaf() calls. I will also try it again with the new information from @rohanorton . 

@Abe404 I am using MAC OS 12.3x. I think we'll be able to get this.

**Comment by Abe404** [comment]
I have been working on this today using an Apple M2 Max. The branch '86-installing-root_trainer-on-an-m1-max-apple-silicon' now contains working code for performing training and inference on an apple GPU using RootPainter.

This is still a work in progress and I have more testing to do. The implementation will likely change, but I wanted to update you here in case you would like to try it out :) 

Testing it out will require installing/running from source. 

I will perform some more in depth tests but training seems fairly quick compared to Colab. For users with a suitable (recent/modern) MacBook I believe this will be a superior solution to using Google Colab and will suffice in many cases.

**Comment by Abe404** [comment]
OK the segment folder function does not work yet. I am working on it. I had to upgrade to PyQt6 to build the client on an M2 Mac. This has a caused a few breaking changes but they aren't very hard to fix.

**Comment by Abe404** [comment]
The segment_folder function is now working again after the changes in the following commit.
https://github.com/Abe404/root_painter/commit/934041784cb67ec6cf21c072e26998f53cb0325d

I'm trying to make a version of the client that builds on an M2 chip so the necessary changes have introduced these bugs. If you want to try this now it might be better just to use the server in this branch and download one of the Mac clients from the releases.

For now I expect everything on the extras menu and measurements menu to crash (in this WIP pyqt6 client). I'll update soon when I have more fixes.

**Comment by ethanbass** [comment]
Would love to get the server running on my M1 mac. I installed the m1 branch from github (86-installing-root_trainer-on-an-m1-max-apple-silicon) and tried to run the `start-trainer` script, but I'm getting an error: 
```
Traceback (most recent call last):
  File "/Users/ethanbass/miniforge3/envs/rootpainter/bin/start-trainer", line 8, in <module>
    sys.exit(start())
  File "/Users/ethanbass/miniforge3/envs/rootpainter/lib/python3.9/site-packages/root_painter_trainer/__init__.py", line 30, in start
    from trainer import Trainer
  File "/Users/ethanbass/miniforge3/envs/rootpainter/lib/python3.9/site-packages/root_painter_trainer/trainer.py", line 241
    def stop_fn()
                 ^
SyntaxError: invalid syntax
```

I'm not very good at python so I'm not sure what's causing the syntax error.  (I also get the same error if I import the start function and try to run it from python). Would appreciate any tips you can offer! Thanks for all your great work on this software -- we've been finding it very useful in our research.

Ethan

**Comment by ethanbass** [comment]
I'm afraid I'm getting a different error now after I tried to start training with the local server. I am using the latest release of the client from the main branch (v 0.2.27). The new error reads:
```execute_instruction start_training
Traceback (most recent call last):
  File "/Users/ethanbass/miniforge3/envs/rootpainter/bin/start-trainer", line 8, in <module>
    sys.exit(start())
  File "/Users/ethanbass/miniforge3/envs/rootpainter/lib/python3.9/site-packages/root_painter_trainer/__init__.py", line 36, in start
    trainer.main_loop()
  File "/Users/ethanbass/miniforge3/envs/rootpainter/lib/python3.9/site-packages/root_painter_trainer/trainer.py", line 125, in main_loop
    self.train_one_epoch()
  File "/Users/ethanbass/miniforge3/envs/rootpainter/lib/python3.9/site-packages/root_painter_trainer/trainer.py", line 247, in train_one_epoch
    train_result = model_utils.epoch(self.model, train_annot_dir, val_annot_dir,
TypeError: epoch() takes 6 positional arguments but 11 were given
```

**Comment by Abe404** [comment]
Hi Ethan,

Thanks for the kind words. 

Thanks for reporting these issues. This branch is a little less stable compared to the master branch, but I'm happy to fix that. 

I'll work on these issues today and will update you again soon.

Kind regards,
Abraham

**Comment by Abe404** [comment]
Syntax error fixed:
https://github.com/Abe404/root_painter/commit/0e6e5aae7587c2ed40904496d3e7a21fe0cbb2f3

My bad. I should have ran the tests/linter before committing this error.

**Comment by ethanbass** [comment]
Thank you very much for looking into this! I am getting a different error now after reinstalling with your new commits:
```
Traceback (most recent call last):
  File "/Users/ethanbass/miniforge3/envs/rootpainter/bin/start-trainer", line 8, in <module>
    sys.exit(start())
  File "/Users/ethanbass/miniforge3/envs/rootpainter/lib/python3.9/site-packages/root_painter_trainer/__init__.py", line 30, in start
    from trainer import Trainer
  File "/Users/ethanbass/miniforge3/envs/rootpainter/lib/python3.9/site-packages/root_painter_trainer/trainer.py", line 39, in <module>
    from multi_epoch.multi_epoch_loader import MultiEpochsDataLoader
ModuleNotFoundError: No module named 'multi_epoch'
```
Not sure where the multi_epoch module is supposed to come from?

**Comment by Abe404** [comment]
The multi_epoch module is found here:
https://github.com/Abe404/root_painter/tree/86-installing-root_trainer-on-an-m1-max-apple-silicon/trainer/multi_epoch

I think the missing multi_module might be an issue related to the method of installation and running using start-trainer.
I should fix this when I make the official release with pip (once this branch gets merged into master) but for now could you try installing and running by doing the following:

```
# download source code for specific mac branch (work in progress)
git clone -b 86-installing-root_trainer-on-an-m1-max-apple-silicon --single-branch https://github.com/Abe404/root_painter.git

# Create an environment for the trainer (to isolate dependencies)
python3 -m venv root_painter/trainer/env

# Activate environment 
source root_painter/trainer/env/bin/activate

# Install environment dependencies for trainer
pip install -r root_painter/trainer/requirements.txt

# Start trainer
python3 root_painter/trainer/main.py
```

**Comment by ethanbass** [comment]
Thanks. I think you're right that it was an installation issue. I was using pip to try to clone the m1 branch from github but it seems like it wasn't installing the multi_epoch folder?  It seems to be working now after following your instructions. Thank you very much! I will update you if I run into any more issues. (Also FIY, I can already see that it's running much much faster from the local server on my computer compared to google colab).

**Comment by Abe404** [comment]
> seems like it wasn't installing the multi_epoch folder? 

Seems like it. I will try to figure out why when I start working on the next pip release.

> It seems to be working now after following your instructions
Ace!

 > I can already see that it's running much much faster from the local server on my computer compared to google colab.

Yes, I think think this is a big deal. I have had a similar experience. My plan is to create a version of RootPainter for Mac where the server is integrated into the client. Basically a stand-alone integrated version which does not require any command line usage. The first step is to get this version released (that still requires some command line usage to install the server with pip etc) and then I will try to create some kind of UI widget to allow the trainer to be managed from within the client.

**Comment by ethanbass** [comment]
The integrate version sounds great. Would definitely make the barrier to entry a lot lower for people who don't want to fiddle around with the command line. Thanks again for all your help!!

**Comment by sporring** [comment]
I had trouble installing root-painter-trainer on a macbook M1 running Macos 15.1. The imagecodecs seemed to be the root of it all, possibly in combination with the python version. Here is what I did to install the server:
```
conda create -n rootPainter python=3.10
conda activate rootPainter
conda install imagecodecs==2021.8.26
pip install root-painter-trainer
start-trainer
```
at which point I get the `Please specify RootPainter sync directory` prompt.

**Comment by Abe404** [comment]
Hi Jon,

The current instructions for getting the RootPainter trainer installed and running on Mac are the following:
https://github.com/Abe404/root_painter/issues/86#issuecomment-1640186063

They seemed to work well for myself and @ethanbass so that's my recommendation for now until I can get these changes into the main release.

Kind regards,
Abraham

**Comment by Abe404** [comment]
Thanks for sharing these details. I will install python3.12 on my Mac and see if I can reproduce the problem (and then fix it).

**Comment by Abe404** [comment]
https://github.com/Abe404/root_painter/commit/fbb2846d23453c38bc407b432396d8f6644c316a is a commit that includes the fixes. Unfortunately this Mac (local training) version is still not as well tested and I am not yet fully confident in it.

**Comment by Abe404** [comment]
this is working great on master branch now.
